// Generated by gencpp from file joint_angle_msgs/joint_angle_node.msg
// DO NOT EDIT!


#ifndef JOINT_ANGLE_MSGS_MESSAGE_JOINT_ANGLE_NODE_H
#define JOINT_ANGLE_MSGS_MESSAGE_JOINT_ANGLE_NODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace joint_angle_msgs
{
template <class ContainerAllocator>
struct joint_angle_node_
{
  typedef joint_angle_node_<ContainerAllocator> Type;

  joint_angle_node_()
    : joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)  {
    }
  joint_angle_node_(const ContainerAllocator& _alloc)
    : joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)  {
  (void)_alloc;
    }



   typedef float _joint1_type;
  _joint1_type joint1;

   typedef float _joint2_type;
  _joint2_type joint2;

   typedef float _joint3_type;
  _joint3_type joint3;

   typedef float _joint4_type;
  _joint4_type joint4;

   typedef float _joint5_type;
  _joint5_type joint5;

   typedef float _joint6_type;
  _joint6_type joint6;




  typedef boost::shared_ptr< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> const> ConstPtr;

}; // struct joint_angle_node_

typedef ::joint_angle_msgs::joint_angle_node_<std::allocator<void> > joint_angle_node;

typedef boost::shared_ptr< ::joint_angle_msgs::joint_angle_node > joint_angle_nodePtr;
typedef boost::shared_ptr< ::joint_angle_msgs::joint_angle_node const> joint_angle_nodeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace joint_angle_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'joint_angle_msgs': ['/home/hiep/Desktop/ros_gazebo_linuxcnc/catkin_ws/src/joint_angle_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b0068422b386ec8608fa05052ffe139f";
  }

  static const char* value(const ::joint_angle_msgs::joint_angle_node_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb0068422b386ec86ULL;
  static const uint64_t static_value2 = 0x08fa05052ffe139fULL;
};

template<class ContainerAllocator>
struct DataType< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joint_angle_msgs/joint_angle_node";
  }

  static const char* value(const ::joint_angle_msgs::joint_angle_node_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 joint1\n\
float32 joint2\n\
float32 joint3\n\
float32 joint4\n\
float32 joint5\n\
float32 joint6\n\
";
  }

  static const char* value(const ::joint_angle_msgs::joint_angle_node_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint1);
      stream.next(m.joint2);
      stream.next(m.joint3);
      stream.next(m.joint4);
      stream.next(m.joint5);
      stream.next(m.joint6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_angle_node_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joint_angle_msgs::joint_angle_node_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::joint_angle_msgs::joint_angle_node_<ContainerAllocator>& v)
  {
    s << indent << "joint1: ";
    Printer<float>::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    Printer<float>::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    Printer<float>::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    Printer<float>::stream(s, indent + "  ", v.joint4);
    s << indent << "joint5: ";
    Printer<float>::stream(s, indent + "  ", v.joint5);
    s << indent << "joint6: ";
    Printer<float>::stream(s, indent + "  ", v.joint6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOINT_ANGLE_MSGS_MESSAGE_JOINT_ANGLE_NODE_H
